#!/bin/bash

# (make sure we can access the parser package)
export CLASSPATH=../../:$CLASSPATH
export TERM=xterm

NLIST_PATH=../../../netlister

cp auto-params-l1b.ctl /tmp
cp fine_routing.ctl /tmp
cp design_rules.dru /tmp
cp design_rules_smd.dru /tmp

##
##
## jython ${NLIST_PATH}/src/netlister.py -i l1b_mk2.v \
##     -l "${NLIST_PATH}/lib/l1b-custom.lib" \
##     -l "${NLIST_PATH}/lib/l1a-custom.lib" \
##     -l "${NLIST_PATH}/lib/xilinx.lib" \
##     -l "${NLIST_PATH}/lib/cpu.lib" \
##     -l "${NLIST_PATH}/lib/rcl.lib" \
##     -l "${NLIST_PATH}/lib/i2c.lib" \
##     -l "${NLIST_PATH}/lib/memory.lib" \
##     -l "${NLIST_PATH}/lib/74series.lib" \
##     -l "${NLIST_PATH}/lib/switches.lib" \
##     -l "${NLIST_PATH}/lib/idc_connectors.lib" \
##     -f scr \
##     -o l1b_mk2.scr \
##     -t l1b_mk2_footer.scr
##
## jython ${NLIST_PATH}/src/netlister.py -i l1b_mk2.v \
##     -l "${NLIST_PATH}/lib/l1b-custom.lib" \
##     -l "${NLIST_PATH}/lib/l1a-custom.lib" \
##     -l "${NLIST_PATH}/lib/xilinx.lib" \
##     -l "${NLIST_PATH}/lib/cpu.lib" \
##     -l "${NLIST_PATH}/lib/rcl.lib" \
##     -l "${NLIST_PATH}/lib/i2c.lib" \
##     -l "${NLIST_PATH}/lib/memory.lib" \
##     -l "${NLIST_PATH}/lib/74series.lib" \
##     -l "${NLIST_PATH}/lib/switches.lib" \
##     -l "${NLIST_PATH}/lib/idc_connectors.lib" \
##     -o l1b_mk2.net \
##     -u \
##     -f net
##
jython ${NLIST_PATH}/src/netlister.py -i beeb816_mk2b.v \
    -l "${NLIST_PATH}/lib/l1b-custom.lib" \
    -l "${NLIST_PATH}/lib/l1a-custom.lib" \
    -l "${NLIST_PATH}/lib/xilinx.lib" \
    -l "${NLIST_PATH}/lib/cpu.lib" \
    -l "${NLIST_PATH}/lib/rcl.lib" \
    -l "${NLIST_PATH}/lib/i2c.lib" \
    -l "${NLIST_PATH}/lib/triac.lib" \
    -l "${NLIST_PATH}/lib/memory.lib" \
    -l "${NLIST_PATH}/lib/74series.lib" \
    -l "${NLIST_PATH}/lib/switches.lib" \
    -l "${NLIST_PATH}/lib/idc_connectors.lib" \
    -f scr \
    -o beeb816_mk2b.scr \
    -t beeb816_mk2b_footer.scr

jython ${NLIST_PATH}/src/netlister.py -i beeb816_mk2b.v \
    -l "${NLIST_PATH}/lib/l1b-custom.lib" \
    -l "${NLIST_PATH}/lib/l1a-custom.lib" \
    -l "${NLIST_PATH}/lib/xilinx.lib" \
    -l "${NLIST_PATH}/lib/cpu.lib" \
    -l "${NLIST_PATH}/lib/rcl.lib" \
    -l "${NLIST_PATH}/lib/i2c.lib" \
    -l "${NLIST_PATH}/lib/triac.lib" \
    -l "${NLIST_PATH}/lib/memory.lib" \
    -l "${NLIST_PATH}/lib/74series.lib" \
    -l "${NLIST_PATH}/lib/switches.lib" \
    -l "${NLIST_PATH}/lib/idc_connectors.lib" \
    -o beeb816_mk2b.net \
    -u \
    -f net
