#!/bin/bash
# ./README [design ] [xc9572|xc95108]
design=level1b_mk2_m
design=cpld_jnr

if [ $# -lt 1 ]; then
    design = level1b_mk2_m
else
    defines=$1
fi


if [ $# -lt 2 ]; then
    target=xc95108-15-pc84
else
    target=$2
fi

defines=""


echo "Building for $target"

BUILD_SCR=../scripts/build.py

${BUILD_SCR}  \
    -a "xst: -define { $defines }"  \
    -m ${design} \
    -d build_${target}_p3_ff \
    -f -t ${target}  \
    -c ${design}.ucf -o speed 
# mv build_${target}_p3_ff/${design}.jed ./${design}_${defines}.jed
#    -a "cpldfit: -pterms 12" \



