#!/bin/bash


# ./README [xc9572|xc95108]


if [ $# -lt 1 ]; then
    target=xc95108
else
    target=$1
fi


if [ $# -lt 2 ]; then
    defines=""
else
    defines=$2
fi


echo "Building for $target"

BUILD_SCR=../scripts/build.py

${BUILD_SCR}  \
       -a "xst: -define { $defines }"  \
       -m level1b_m \
       -d build_${target}_p3_ff \
       -f -t ${target}-15-pc84  \
       -c constraints/level1b_m.ucf -o speed
mv build_${target}_p3_ff/level1b_m.jed ./level1b_m_${defines}.jed




