#!/bin/tcsh -fv


set BUILD_SCR =  ../scripts/build.py

${BUILD_SCR}  \
       -a "xst: -define { }"  \
       -m level1b_m \
       -d build_xc95108_p3_ff \
       -f -t xc95108-10-pc84  \
       -c level1b_m.ucf -o speed


